<div class="section text-center">
    <div class="container">
        <div class="row">
            <div class="col-md-8 ml-auto mr-auto">
                <h2 class="title">Vamos falar de produto</h2>
                <h5 class="description">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    Nulla id erat lorem. Duis metus magna, maximus eu interdum nec, fringilla volutpat ligula.
                    Sed interdum arcu nunc, ut finibus nisi auctor hendrerit.
                    Praesent ut nisi eget urna pharetra euismod et aliquet elit.
                    Proin lacinia, ipsum quis semper molestie, metus ligula ultrices purus, nec dapibus magna elit non sapien.
                </h5>
                <br>
                <a href="#paper-kit" class="btn btn-danger btn-round">
                    Veja mais
                </a>
            </div>
        </div>
        <br/>
        <br/>
        <div class="row">
            <div class="col-md-3">
                <div class="info">
                    <div class="icon icon-danger">
                        <i class="nc-icon nc-album-2"></i>
                    </div>
                    <div class="description">
                        <h4 class="info-title">Galeria</h4>
                        <p class="description">
                            Nulla id erat lorem. Duis metus magna, maximus eu interdum nec, fringilla volutpat ligula.
                        </p>
                        <a href="javascript:;" class="btn btn-link btn-danger">Veja mais</a>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="info">
                    <div class="icon icon-danger">
                        <i class="nc-icon nc-bulb-63"></i>
                    </div>
                    <div class="description">
                        <h4 class="info-title">Novas Ideias</h4>
                        <p>
                            Nulla id erat lorem. Duis metus magna, maximus eu interdum nec, fringilla volutpat ligula.
                        </p>
                        <a href="javascript:;" class="btn btn-link btn-danger">Veja mais</a>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="info">
                    <div class="icon icon-danger">
                        <i class="nc-icon nc-chart-bar-32"></i>
                    </div>
                    <div class="description">
                        <h4 class="info-title">Estatisticas</h4>
                        <p>
                            Nulla id erat lorem. Duis metus magna, maximus eu interdum nec, fringilla volutpat ligula.
                        </p>
                        <a href="javascript:;" class="btn btn-link btn-danger">Veja mais</a>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="info">
                    <div class="icon icon-danger">
                        <i class="nc-icon nc-sun-fog-29"></i>
                    </div>
                    <div class="description">
                        <h4 class="info-title">Design</h4>
                        <p>
                            Nulla id erat lorem. Duis metus magna, maximus eu interdum nec, fringilla volutpat ligula.
                        </p>
                        <a href="javascript:;" class="btn btn-link btn-danger">Veja mais</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

