<div class="page-header" data-parallax="true" style="background-image: url('../assets/img/daniel-olahh.jpg');">
    <div class="filter"></div>
    <div class="container">
        <div class="motto text-center">
            <h1>Web PHP MVC</h1>
            <h3>Mini framework com PHP 7.4</h3>
            <br/>
        </div>
    </div>
</div>

<div class="main">
    <div class="section landing-section">
        <div class="container">
            <div class="row">
                <div class="col-md-8 ml-auto mr-auto">
                    <?php if ($this->params) { ?>
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            <strong><?= $this->params['msg']?></strong>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    <?php } ?>
                </div>
            </div>

            <div class="row">
                <div class="col-md-8 ml-auto mr-auto">
                    <h2 class="text-center">Escrever Mensagem</h2>

                    <form class="contact-form">
                        <div class="row">
                            <div class="col-md-6">
                                <label>Nome <span class="text-danger">*</span></label>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                    <span class="input-group-text">
                                        <i class="nc-icon nc-single-02"></i>
                                    </span>
                                    </div>
                                    <input pattern="[A-Za-záàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ ]+$" required="true" type="text" name="nome" id="nome" class="form-control" placeholder="Nome">
                                </div>
                            </div>

                            <div class="col-md-6">
                                <label>E-mail <span class="text-danger">*</span></label>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                    <span class="input-group-text">
                                        <i class="nc-icon nc-email-85"></i>
                                    </span>
                                    </div>
                                    <input type="email" name="email" id="email" required="true" class="form-control" placeholder="E-mail">
                                </div>
                            </div>
                        </div>

                        <label>Mensagem <span class="text-danger">*</span></label>
                        <textarea class="form-control" maxlength="350" required="true" rows="4" name="mensagem" id="mensagem" placeholder="Escreva sua mensagem..."></textarea>

                        <div class="row">
                            <div class="col-md-4 ml-auto mr-auto text-center">
                                <button class="btn btn-danger btn-lg btn-fill" type="button" onclick="salvarMensagem()">Enviar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function salvarMensagem() {
        var nome = document.getElementById('nome').value;
        var email = document.getElementById('email').value;
        var mensagem = document.getElementById('mensagem').value;

        if ((nome === undefined || nome === '') || (email === undefined || email === '') || (mensagem === undefined || mensagem === '')) {
            toastr.warning('Todos os campos são obrigatórios!');
            return;
        }

        var data = {
            'nome': nome,
            'email': email,
            'mensagem': mensagem
        }

        $.ajax({
            type: "POST",
            url: "/salvar-mensagem",
            data: data,
            success: function(msg){
                mensagem = JSON.parse(msg);
                toastr.success(mensagem.success);
            },
            error: function(err){
                mensagem = JSON.parse(err);
                toastr.warning(mensagem.error);
            }
        });
    }
</script>