<!doctype html>

<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="apple-touch-icon" sizes="76x76" href="assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="assets/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>

    <title>Web PHP 7.4 - MVC</title>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no'
          name='viewport'/>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet"/>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href="../assets/css/bootstrap.min.css" rel="stylesheet"/>
    <link href="../assets/css/paper-kit.css?v=2.2.0" rel="stylesheet"/>
    <link href="../assets/demo/demo.css" rel="stylesheet"/>
    <link href="../assets/demo/demo.css" rel="stylesheet"/>
    <link href="../assets/css/toastr.min.css" rel="stylesheet"/>
</head>
<body class="landing-page sidebar-collapse">
    <nav class="navbar navbar-expand-lg fixed-top navbar-transparent " color-on-scroll="300">
        <div class="container">
            <div class="navbar-translate">
                <a class="navbar-brand" href="" rel="tooltip"
                   title="Web PHP MVC" data-placement="bottom">
                    Web PHP MVC
                </a>
                <button class="navbar-toggler navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
                        aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-bar bar1"></span>
                    <span class="navbar-toggler-bar bar2"></span>
                    <span class="navbar-toggler-bar bar3"></span>
                </button>
            </div>

            <div class="collapse navbar-collapse justify-content-end" id="navigation">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="/" class="nav-link">
                            <i class="nc-icon nc-layout-11"></i> Home
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="/sobre" class="nav-link">
                            <i class="nc-icon nc-book-bookmark"></i> Sobre
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="/mensagem" class="nav-link">
                            <i class="nc-icon nc-email-85"></i> Mensagem
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <?= $this->content() ?>

    <footer class="footer footer-white">
        <div class="container">
            <div class="row">
                <nav class="footer-nav">
                    <ul>
                        <li>
                            <a href="#">Home</a>
                        </li>
                        <li>
                            <a href="#">Sobre</a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </footer>

    <script src="../assets/js/core/jquery.min.js" type="text/javascript"></script>
    <script src="../assets/js/core/popper.min.js" type="text/javascript"></script>
    <script src="../assets/js/core/bootstrap.min.js" type="text/javascript"></script>
    <script src="../assets/js/plugins/bootstrap-switch.js"></script>
    <script src="../assets/js/plugins/nouislider.min.js" type="text/javascript"></script>
    <script src="../assets/js/plugins/moment.min.js"></script>
    <script src="../assets/js/plugins/bootstrap-datepicker.js" type="text/javascript"></script>
    <script src="../assets/js/paper-kit.js?v=2.2.0" type="text/javascript"></script>
    <script src="../assets/js/toastr.min.js"></script>
</body>
</html>
